ppv3:
  ppv3_url: 'https://ppv3-test.yeastar.com'
  client_id: 'ppv3'
  client_secret: 'Yeastar123'
  grant_type: 'password'
  username: 'pp-d1@yeastar.com'
  password: 'Yeastar123'

  log_level: 'debug'
  log_extension: '.log'

tianqi:
  tianqi_url: 'http://v1.yiketianqi.com/api'
  appid: '78117444'
  appsecret: '7PeAXEv3'

log:
  log_dir: 'logs'
  log_level: 'debug'
  log_extension: '.log'


#---
#ppv3_2:
#  client_id: 'ppv3_2'